name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 6 * * 3,6'  # Runs at midnight every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API request to Supabase
        run: |
          curl -X GET "https://cdkmzodjgvxnuijsqtbh.supabase.co/rest/v1/" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka216b2RqZ3Z4bnVpanNxdGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MDc4ODMsImV4cCI6MjA0NjQ4Mzg4M30.6JbmCKMEBQH6AnFc0_J5_LRoAi2LC2NioQXEYVmMzu8" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka216b2RqZ3Z4bnVpanNxdGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MDc4ODMsImV4cCI6MjA0NjQ4Mzg4M30.6JbmCKMEBQH6AnFc0_J5_LRoAi2LC2NioQXEYVmMzu8"
          
